spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations:
            - classpath:config/core/{application}
            - classpath:config/infra/{application}
            - classpath:config/stats/{application}

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/

server:
  port: 0