analyzer:
  kafka:
    user-actions-properties:
      "bootstrap.servers": kafka:29092
      "group.id": analyzer-user-actions-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.UserActionsDeserializer
    event-similarity-properties:
      "bootstrap.servers": localhost:9092
      "group.id": analyzer-event-similarity-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.EventSimilarityDeserializer
    topics:
      user-actions: stats.user-actions.v1
      event-similarity: stats.events-similarity.v1


grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext