spring:
  application:
    name: main-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

stats-service:
  url: http://localhost:9090

server:
  port: 0
